camera:
  source: rtsp://192.168.1.100:8080/h264_pcm.sdp
zones:
- zone_id: zone_entrance_exit
  zone_type: entry_exit
  polygon:
  - - 42
    - 0
  - - 639
    - 14
  - - 572
    - 477
  - - 78
    - 479
  label: Main Entrance
low_stock_confidence_threshold: 0.6
queue_congestion_length: 4
